use_frameworks!

platform :ios, '8.0'

target 'Network-Lib-Demo_Example' do
  pod 'Network-Lib-Demo', :path => '../'

  target 'Network-Lib-Demo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
